title: <p> align="center">Aaron Phaneuf</p> # your name (or website title) here
logo: "/images/aphaneuf.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">Pricing Manager for Planet Organic Market</p>
  <br><br>
  Specializing in data science through Python
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
